name: SheriaPlatform

x-common-config: &common-config
  env_file:
    - .env
  networks:
    - sheria_network
x-common-fastapi-config: &common-fastapi-config
  <<: *common-config
  image: sheria_rag_service:latest
  build:
    context: .
    dockerfile: services/api/Dockerfile
  volumes:
    - .:/app
  networks:
    - sheria_network

services:
  rag_fastapi_backend:
    <<: *common-fastapi-config
    container_name: rag_fastapi_backend
    command: python services/api/dev.py
    restart: always
    ports:
      - "8000:8000"

networks:
  sheria_network:
