# deploy/secrets/external-secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
spec:
  refreshInterval: 1h             # Check for rotation every hour
  secretStoreRef:
    name: aws-secrets-manager     # Connects to AWS
    kind: ClusterSecretStore
  target:
    name: app-env-secret          # Creates a K8s Secret named 'app-env-secret'
  data:
  - secretKey: NEO4J_PASSWORD
    remoteRef:
      key: prod/rag/db_creds      # AWS Secret Name
      property: neo4j_password